- name: copy module
  hosts: test
  become: yes
  gather_facts: no
  vars:
    text: good morning
    text1: Devops
    package: httpd
  tasks:
    - name: copy the file from source to destination
      template:
        src: /home/lokeshchand/lokesh.sh.j2
        dest: /home/lokeshchand
    - name: running the shell script
      shell: sh /home/lokeshchand/lokesh.sh.j2
      register: output
    - name: printing the shell script output
      debug:
       msg: "{{output}}"      
        